INSERT INTO subjects (subject_Id, subject) values ('S0',  'Math' );
INSERT INTO subjects (subject_Id, subject) values ('S1',  'English' );
INSERT INTO subjects (subject_Id, subject) values ('S2',  'Proofreading' );
INSERT INTO subjects (subject_Id, subject) values ('S3',  'Accounting' );
INSERT INTO subjects (subject_Id, subject) values ('S4',  'Computer Science' );
INSERT INTO subjects (subject_Id, subject) values ('S5',  'Electrical Engineering' );
INSERT INTO subjects (subject_Id, subject) values ('S6',  'History' );
INSERT INTO subjects (subject_Id, subject) values ('S7',  'Blackboard' );
INSERT INTO subjects (subject_Id, subject) values ('S8',  'General Computer Help' );
INSERT INTO subjects (subject_Id, subject) values ('S9',  'Microsoft Applications' );
INSERT INTO subjects (subject_Id, subject) values ('S10',  'Business Management' );
INSERT INTO subjects (subject_Id, subject) values ('S11',  'Microbiology' );
INSERT INTO subjects (subject_Id, subject) values ('S12',  'Critical Thinking' );
INSERT INTO subjects (subject_Id, subject) values ('S13',  'Engineering' );
INSERT INTO subjects (subject_Id, subject) values ('S14',  'Psychology' );
INSERT INTO subjects (subject_Id, subject) values ('S15',  'Economics' );
INSERT INTO subjects (subject_Id, subject) values ('S16',  'Chemistry' );
INSERT INTO subjects (subject_Id, subject) values ('S17',  'Earth Science' );
INSERT INTO subjects (subject_Id, subject) values ('S18',  'CADD' );
INSERT INTO subjects (subject_Id, subject) values ('S19',  'Early Childhood Education' );
INSERT INTO subjects (subject_Id, subject) values ('S20',  'Sociology' );
INSERT INTO subjects (subject_Id, subject) values ('S21',  'A and P' );
INSERT INTO subjects (subject_Id, subject) values ('S22',  'Medical Terminology' );
INSERT INTO subjects (subject_Id, subject) values ('S23',  'Marketing' );
INSERT INTO subjects (subject_Id, subject) values ('S24',  'Biology' );
INSERT INTO subjects (subject_Id, subject) values ('S25',  'Physics' );
INSERT INTO subjects (subject_Id, subject) values ('S26',  'APA' );
INSERT INTO subjects (subject_Id, subject) values ('S27',  'MLA' );
