@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initRoles/accountant.sql'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initRoles/administrator.sql'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initRoles/gateKeeper.sql'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initRoles/marketer.sql'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initRoles/researcher.sql'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initRoles/tutor.sql'
