@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initTables/contacts/1 init contacts'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initTables/expenseList/1 init expenseList'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initTables/expenses/1 init expenses'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initTables/locationList/1 init locationList'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initTables/logs/1 init logs'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initTables/payments/1 init payments'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initTables/subjectList/1 init subjectList'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initTables/tutors/1 init tutors'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initTables/intermediateTables/createTable rs_contact_location'
@'C:\Users\James\Desktop\Oracle\tutoringSchema\radiosilence\initTables/intermediateTables/createTable rs_contact_subject'